name: isolated-env

services:
  python-3:
    image: python-env
    build: ./env-config/
    volumes:
      - type: bind
        source: ./dsa/
        target: /dsa
    working_dir: /dsa
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    entrypoint: sh

